security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            user_checker: App\Security\UserChecker
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
                target: app_home

    role_hierarchy:
        ROLE_EMPLOYE: ROLE_USER
        ROLE_ADMIN: [ROLE_EMPLOYE, ROLE_USER]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/utilisateur, roles: ROLE_USER }
        - { path: ^/commande, roles: ROLE_USER }
